# Generated by Django 2.0.7 on 2018-07-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=9, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('role', models.CharField(max_length=20, verbose_name='期望职位')),
                ('age', models.PositiveSmallIntegerField(default='30', verbose_name='年龄')),
                ('companies', models.CharField(blank=True, max_length=100, verbose_name='曾就职公司')),
                ('funding', models.CharField(blank=True, max_length=20, verbose_name='期望轮次')),
                ('current_salary', models.CharField(blank=True, max_length=20, verbose_name='目前薪资')),
                ('expected_salary', models.CharField(blank=True, max_length=30, verbose_name='期望薪资')),
                ('remarks', models.TextField(blank=True, max_length=100, verbose_name='推荐人评语')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resume_link', models.URLField(blank=True, verbose_name='简历链接')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='职位名称')),
                ('supervisor', models.CharField(max_length=20, verbose_name='汇报线')),
                ('salary', models.CharField(max_length=50, verbose_name='薪资范围')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='状态')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='招聘者')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs_Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='公司名称')),
                ('company_description', models.TextField(verbose_name='公司介绍')),
                ('company_address', models.CharField(blank=True, max_length=50, verbose_name='公司地址')),
                ('company_size', models.CharField(blank=True, max_length=20, verbose_name='公司人员规模')),
                ('wechat_id', models.CharField(blank=True, max_length=20, verbose_name='微信号')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='自我介绍')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Education', verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Function', verbose_name='职能'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='function_multi',
            field=models.ManyToManyField(related_name='function_multi', to='hello.Function'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Industry', verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Province', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Sex', verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Candidate_Status', verbose_name='状态'),
        ),
    ]
